spring:
  application:
    name: sensor-data-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name}

server:
  port: 8082
